In [74]:
import numpy  as np
import pandas as pd

In [75]:
data1 = {
    'id': [1, 2],
    'name': ['Ajay', 'Drishan']
}
df1 = pd.DataFrame(data1)

In [76]:
data2 = {
    'id': [1, 3],
    'dept': ['Analytics', 'Tech']
}
df2 = pd.DataFrame(data2)

In [77]:
df1

   id     name
0   1     Ajay
1   2  Drishan

In [78]:
df2

   id       dept
0   1  Analytics
1   3       Tech

In [79]:
pd.merge(df1, df2, how = 'inner', on = 'id')

   id  name       dept
0   1  Ajay  Analytics

In [80]:
pd.merge(df1, df2, how = 'left', on = 'id')

   id     name       dept
0   1     Ajay  Analytics
1   2  Drishan        NaN

In [81]:
pd.merge(df1, df2, how = 'right', on = 'id')

   id  name       dept
0   1  Ajay  Analytics
1   3   NaN       Tech

In [82]:
pd.merge(df1, df2, how = 'outer', on = 'id')

   id     name       dept
0   1     Ajay  Analytics
1   2  Drishan        NaN
2   3      NaN       Tech

In [83]:
data1 = {
    'id1': [1, 2],
    'name': ['Ajay', 'Drishan']
}
df1 = pd.DataFrame(data1)

In [84]:
data2 = {
    'id2': [1, 3],
    'dept': ['Analytics', 'Tech']
}
df2 = pd.DataFrame(data2)

In [85]:
df1

   id1     name
0    1     Ajay
1    2  Drishan

In [86]:
df2

   id2       dept
0    1  Analytics
1    3       Tech

In [87]:
# pd.merge(df1,df2,how='inner',on='id') # error

In [88]:
pd.merge(df1, df2, how = 'inner', left_on = 'id1', right_on = 'id2')

   id1  name  id2       dept
0    1  Ajay    1  Analytics

In [89]:
pd.merge(df1, df2, how = 'inner', left_on = 'id1', right_on = 'id2')

   id1  name  id2       dept
0    1  Ajay    1  Analytics

In [90]:
# Customers DataFrame
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "order_id": ["A", "B", "C", "D"],
    "city": ["Bangalore", "Delhi", "Mumbai", "Chennai"]
})

# Orders DataFrame
df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [1, 2, 3, 5],
    "amount": [500, 300, 200, 700]
})

print(df_customers)
print('-'*32)
print(df_orders)

   customer_id order_id       city
0            1        A  Bangalore
1            2        B      Delhi
2            3        C     Mumbai
3            4        D    Chennai
--------------------------------
   order_id  customer_id  amount
0       101            1     500
1       102            2     300
2       103            3     200
3       104            5     700

In [91]:
pd.merge(df_customers,df_orders, how='inner',on='customer_id')

   customer_id order_id_x       city  order_id_y  amount
0            1          A  Bangalore         101     500
1            2          B      Delhi         102     300
2            3          C     Mumbai         103     200

In [92]:
pd.merge(df_customers,df_orders, how='inner',on='customer_id',
         suffixes=('_left','_right'))

   customer_id order_id_left       city  order_id_right  amount
0            1             A  Bangalore             101     500
1            2             B      Delhi             102     300
2            3             C     Mumbai             103     200

In [93]:
# T3: colors
t3 = pd.DataFrame({
    "colors": ["red", "blue"]
})

# T4: sizes
t4 = pd.DataFrame({
    "sizes": ["S", "M", "L", "XL"]
})

print(t3)
print('-'*32)
print(t4)

  colors
0    red
1   blue
--------------------------------
  sizes
0     S
1     M
2     L
3    XL

In [94]:
pd.merge(t3,t4,how='cross')

  colors sizes
0    red     S
1    red     M
2    red     L
3    red    XL
4   blue     S
5   blue     M
6   blue     L
7   blue    XL

In [95]:
df1=pd.DataFrame(
    {"letter":["a","b","c"],
     "num":range(3)})
df2=pd.DataFrame(
    {"value":[3,5,7]},
    index=["a","b","e"])

In [96]:
df1

  letter  num
0      a    0
1      b    1
2      c    2

In [97]:
df2

   value
a      3
b      5
e      7

In [98]:
# col - index join as well!

In [99]:
pd.merge(df1,df2,how='inner',left_on = 'letter',right_index=True)

  letter  num  value
0      a    0      3
1      b    1      5

In [100]:
# index - index
# left_index = True,right_index=True

In [101]:
df1 = pd.DataFrame({
    "name": ["A", "B", "C"],
    "score": [80, 85, 90]
})

df2 = pd.DataFrame({
    "name": ["D", "E"],
    "score": [70, 75]
})

print(df1)
print('-'*32)
print(df2)

  name  score
0    A     80
1    B     85
2    C     90
--------------------------------
  name  score
0    D     70
1    E     75

In [102]:
# Row-wise
pd.concat([df1,df2], axis = 0)

  name  score
0    A     80
1    B     85
2    C     90
0    D     70
1    E     75

In [103]:
pd.concat([df1,df2], axis = 0,ignore_index=True)

  name  score
0    A     80
1    B     85
2    C     90
3    D     70
4    E     75

In [104]:
pd.concat([df1,df2], axis = 1)
# can add - ignore_index=True

  name  score name  score
0    A     80    D   70.0
1    B     85    E   75.0
2    C     90  NaN    NaN

# Question Practise

In [105]:
import pandas as pd

# Customers
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "name": ["A", "B", "C", "D", "E"],
    "city": ["Bangalore", "Delhi", "Mumbai", "Chennai", "Hyderabad"]
})

# Orders
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106],
    "customer_id": [1, 2, 2, 3, 6, 2],
    "amount": [500, 300, 200, 400, 800, 150]
})

# Payments
payments = pd.DataFrame({
    "payment_id": [201, 202, 203, 204],
    "order_id": [101, 102, 104, 107],
    "status": ["Paid", "Pending", "Paid", "Failed"]
})

In [106]:
# Q1. Inner Join Basics
# Merge customers and orders to show only customers who have placed orders.
# Output: customer_id, name, order_id, amount

In [107]:
# @title
q1 = pd.merge(customers, orders, on="customer_id", how="inner")[["customer_id", "name", "order_id", "amount"]]
print(q1)

   customer_id name  order_id  amount
0            1    A       101     500
1            2    B       102     300
2            2    B       103     200
3            2    B       106     150
4            3    C       104     400

In [108]:
# Q2. Left Join (Unmatched Handling)
# Show all customers and their orders (if any).
# Identify customers who never placed an order

In [109]:
# @title
q2 = pd.merge(customers, orders, on="customer_id", how="left")
print(q2)

   customer_id name       city  order_id  amount
0            1    A  Bangalore     101.0   500.0
1            2    B      Delhi     102.0   300.0
2            2    B      Delhi     103.0   200.0
3            2    B      Delhi     106.0   150.0
4            3    C     Mumbai     104.0   400.0
5            4    D    Chennai       NaN     NaN
6            5    E  Hyderabad       NaN     NaN

In [110]:
# Q3. Right Join Insight
# Show all orders with customer details.
# Find orders that do not have a valid customer

In [111]:
# @title
q3 = pd.merge(customers, orders, on="customer_id", how="right")
print(q3)

   customer_id name       city  order_id  amount
0            1    A  Bangalore       101     500
1            2    B      Delhi       102     300
2            2    B      Delhi       103     200
3            3    C     Mumbai       104     400
4            6  NaN        NaN       105     800
5            2    B      Delhi       106     150

In [112]:
# @title
invalid_orders = q3[q3["name"].isna()][["order_id", "customer_id"]]
print(invalid_orders)

   order_id  customer_id
4       105            6

In [113]:
# Q4. Full Outer Join Analysis
# Perform an outer join between customers and orders.
# Count how many rows have missing values
# Explain why they occur

In [114]:
# @title
q4 = pd.merge(customers, orders, on="customer_id", how="outer")
print(q4)
missing_count = q4.isna().sum().sum()
print("-----------------------")
print(missing_count)

   customer_id name       city  order_id  amount
0            1    A  Bangalore     101.0   500.0
1            2    B      Delhi     102.0   300.0
2            2    B      Delhi     103.0   200.0
3            2    B      Delhi     106.0   150.0
4            3    C     Mumbai     104.0   400.0
5            4    D    Chennai       NaN     NaN
6            5    E  Hyderabad       NaN     NaN
7            6  NaN        NaN     105.0   800.0
-----------------------
6

In [115]:
# @title
temp = pd.merge(customers, orders, on="customer_id", how="inner")

q5 = pd.merge(temp, payments, on="order_id", how="left")[
    ["name", "order_id", "amount", "status"]
]
print(q5)

  name  order_id  amount   status
0    A       101     500     Paid
1    B       102     300  Pending
2    B       103     200      NaN
3    B       106     150      NaN
4    C       104     400     Paid

In [116]:
# Q6. Cross Join Challenge 🔥
# Create all possible combinations of:
# customers × payment status
# Questions:
# Total number of rows?
# Why is this useful?

In [117]:
# @title
q6 = customers.merge(payments, how="cross")
print(q6)

    customer_id name       city  payment_id  order_id   status
0             1    A  Bangalore         201       101     Paid
1             1    A  Bangalore         202       102  Pending
2             1    A  Bangalore         203       104     Paid
3             1    A  Bangalore         204       107   Failed
4             2    B      Delhi         201       101     Paid
5             2    B      Delhi         202       102  Pending
6             2    B      Delhi         203       104     Paid
7             2    B      Delhi         204       107   Failed
8             3    C     Mumbai         201       101     Paid
9             3    C     Mumbai         202       102  Pending
10            3    C     Mumbai         203       104     Paid
11            3    C     Mumbai         204       107   Failed
12            4    D    Chennai         201       101     Paid
13            4    D    Chennai         202       102  Pending
14            4    D    Chennai         203       104     Paid
15            4    D    Chennai         204       107   Failed
16            5    E  Hyderabad         201       101     Paid
17            5    E  Hyderabad         202       102  Pending
18            5    E  Hyderabad         203       104     Paid
19            5    E  Hyderabad         204       107   Failed

In [118]:
# Q7. Overlapping Columns + Cleanup
# Create a new DataFrame:
# customer_info = customers.rename(columns={"city": "location"})
# Now:
# Merge customers and customer_info
# Handle duplicate columns properly
# Clean final output (no _x, _y)

In [119]:
# @title
customer_info = customers.rename(columns={"city": "location"})

q7 = pd.merge(customers, customer_info, on="customer_id")
print(q7)
print("--------------------------------------")

# Clean duplicate columns
q7 = q7.drop(columns=["name_y"]).rename(columns={"name_x": "name"})

print(q7)

   customer_id name_x       city name_y   location
0            1      A  Bangalore      A  Bangalore
1            2      B      Delhi      B      Delhi
2            3      C     Mumbai      C     Mumbai
3            4      D    Chennai      D    Chennai
4            5      E  Hyderabad      E  Hyderabad
--------------------------------------
   customer_id name       city   location
0            1    A  Bangalore  Bangalore
1            2    B      Delhi      Delhi
2            3    C     Mumbai     Mumbai
3            4    D    Chennai    Chennai
4            5    E  Hyderabad  Hyderabad